# PARAMETERS TO CONTROL THE BEHAVIOR OF THE GAME ENGINE
# DO NOT REMOVE OR RENAME THIS FILE
PLAYER_1_NAME = 'STARTER BOT'
PLAYER_1_PATH = './starter_bot'
# NO TRAILING SLASHES ARE ALLOWED IN PATHS
PLAYER_2_NAME = 'PLAYGROUND'
PLAYER_2_PATH = './playground_bot'
# GAME PROGRESS IS RECORDED HERE
GAME_LOG_FILENAME = 'gamelog'
# PLAYER_LOG_SIZE_LIMIT IS IN BYTES
PLAYER_LOG_SIZE_LIMIT = 524288
# STARTING_GAME_CLOCK AND TIMEOUTS ARE IN SECONDS
ENFORCE_GAME_CLOCK = False
STARTING_GAME_CLOCK = 30000.
BUILD_TIMEOUT = 30000.
CONNECT_TIMEOUT = 30000.
# THE GAME VARIANT FIXES THE PARAMETERS BELOW
# CHANGE ONLY FOR TRAINING OR EXPERIMENTATION
NUM_ROUNDS = 100
STARTING_STACK = 200
BIG_BLIND = 2
SMALL_BLIND = 1
